version: 2.1 # Pakai CircleCI config version 2.1

jobs: # Daftar tugas (jobs) yang akan dijalankan

  lint-dockerfile: # Job pertama: linting Dockerfile
    docker:
      - image: cimg/base:2024.01 # Pakai base image CircleCI
    steps:
      - checkout # Ambil source code dari repo
      - run:
          name: Install Hadolint # Install hadolint untuk cek Dockerfile
          command: |
            sudo curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
            sudo chmod +x /usr/local/bin/hadolint
      - run:
          name: Lint Dockerfile # Jalankan hadolint ke Dockerfile
          command: hadolint Dockerfile

  build-app-karsajobs-ui: # Job kedua: build dan push image karsajobs-ui
    docker:
      - image: cimg/base:2024.01 # Pakai base image CircleCI
    steps:
      - checkout
      - setup_remote_docker # Setup Docker daemon untuk bisa build/push image
      - run:
          name: Login to GHCR # Login ke GitHub Container Registry (GHCR)
          command: |
            echo "$GHCR_TOKEN" | docker login ghcr.io -u mmaulidinabdi --password-stdin
      - run:
          name: Build and Push # Build dan push docker image ke GHCR
          command: |
            docker build -t ghcr.io/mmaulidinabdi/karsajobs-ui:latest .
            docker push ghcr.io/mmaulidinabdi/karsajobs-ui:latest 

workflows: # Urutan jalan job
  karsajobs-ui-workflow:
    jobs:
      - lint-dockerfile # Pertama lint Dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile # Build dan push hanya kalau lint sukses
          context: ghcr-credentials # Pakai context untuk ambil token GHCR
