version: 2.1
jobs: # Daftar tugas (jobs) yang akan dijalankan

  lint-dockerfile:
    docker:
      - image: cimg/base:2024.01  # Gunakan image dasar (base) CircleCI
    steps:
      - checkout                  # Clone source code dari repository
      - run:
          name: Install Hadolint  # Install Hadolint untuk memeriksa Dockerfile
          command: |
            sudo curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
            sudo chmod +x /usr/local/bin/hadolint
      - run:
          name: Lint Dockerfile    # Jalankan linting pada Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: cimg/go:1.21        # Gunakan image Go 1.21 
    steps:
      - checkout                   # Clone source code dari repository
      - run:
          name: Run Unit Tests     # Jalankan unit test untuk aplikasi Go
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:2024.01    # Gunakan image dasar CircleCI
    steps:
      - checkout                    # Clone source code dari repository
      - setup_remote_docker         # Setup remote Docker engine untuk build image
      - run:
          name: Login to GHCR        # Login ke GitHub Container Registry
          command: |
            echo "$GHCR_TOKEN" | docker login ghcr.io -u mmaulidinabdi --password-stdin
      - run:
          name: Build and Push       # Build Docker image dan Push ke GHCR
          command: |
            docker build -t ghcr.io/mmaulidinabdi/karsajobs:latest .
            docker push ghcr.io/mmaulidinabdi/karsajobs:latest

workflows:
  karsajobs-workflow:
    jobs:
      - lint-dockerfile             # Job pertama: lint Dockerfile
      - test-app:
          requires:
            - lint-dockerfile        # Hanya jalan kalau lint berhasil
      - build-app-karsajobs:
          requires:
            - test-app               # Hanya jalan kalau unit test berhasil
          context: ghcr-credentials  # Menggunakan context untuk variabel rahasia (GHCR_USERNAME dan GHCR_TOKEN)
